import type { CollectionMap, CollectionName } from "./schemas";

/**
 * Initial content used until an administrator saves changes (which writes to
 * CONTENT_DIR). Editorial destination copy is general and non-absolute.
 *
 * - Universities are SAMPLE entries (`sample: true`) of well-known public
 *   institutions for layout/search development. They are informational only,
 *   imply NO partnership, and fees/requirements must be verified before launch.
 * - Dream Stories, Reviews and Team are intentionally EMPTY: only real,
 *   consented content may be added through the admin dashboard.
 */
const t = "2026-01-01T00:00:00.000Z";
const meta = { published: true, createdAt: t, updatedAt: t };

export const seed: { [K in CollectionName]: CollectionMap[K][] } = {
  homepage: [
    {
      id: "homepage",
      ...meta,
      heroHeadline: "Your journey to Europe starts here.",
      heroSubheadline: "Study. Explore. Build your future.",
      heroMessage:
        "Discover study opportunities across Germany and selected European destinations with professional guidance from application to arrival.",
      introStatement:
        "AVIORA EDU guides ambitious students from Pakistan, India, the UAE, Saudi Arabia and Bangladesh toward the right university in Europe — with a transparent process, honest advice and support that continues after you land.",
      aboutWho:
        "AVIORA EDU is an education consultancy focused on Germany and a small, deliberately chosen set of European study destinations: Italy, Poland, Portugal and Austria.",
      aboutWhat:
        "We help students assess their profile, shortlist suitable universities and programmes, prepare strong application documents, understand visa requirements and plan for life in Europe.",
      aboutWhy:
        "We keep our focus narrow so our guidance can be deep. We explain requirements plainly, never promise outcomes we do not control, and stay with students from the first conversation to their first weeks abroad.",
    },
  ],

  destinations: [
    {
      id: "germany",
      ...meta,
      name: "Germany",
      country: "Germany",
      slug: "germany",
      flag: "DE",
      primary: true,
      order: 0,
      tagline: "Research-driven universities at the heart of Europe.",
      description:
        "Germany combines internationally respected public universities, a strong research culture and one of Europe's largest economies. Many programmes are taught in English at master's level, and most public universities charge low or no tuition fees for the majority of programmes — though a semester contribution applies and some federal states or universities charge non-EU students.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Public universities with low or no tuition for most programmes (rules vary by state)",
        "Strong engineering, computer science, natural science and business faculties",
        "Universities of Applied Sciences with practice-oriented, industry-linked degrees",
        "Post-study residence permit options to search for work after graduation",
        "Degrees recognised across the European Higher Education Area",
      ],
      lifestyle: [
        "Excellent public transport and semester tickets in many cities",
        "Large international student communities in Berlin, Munich, Hamburg and beyond",
        "Central location for travel across Europe",
      ],
      cities: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Aachen", "Heidelberg", "Stuttgart", "Cologne"],
      universities: [],
    },
    {
      id: "italy",
      ...meta,
      name: "Italy",
      country: "Italy",
      slug: "italy",
      flag: "IT",
      primary: false,
      order: 1,
      tagline: "Historic universities, design, architecture and engineering.",
      description:
        "Italy is home to some of the world's oldest universities alongside modern technical institutes. Public universities often use income-based tuition, and a growing number of degrees are taught in English.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Income-based tuition at many public universities",
        "Strengths in architecture, design, engineering and economics",
        "Regional scholarship schemes for eligible students",
      ],
      lifestyle: ["Rich cultural life and heritage cities", "Mediterranean climate and cuisine"],
      cities: ["Milan", "Rome", "Bologna", "Turin", "Padua"],
      universities: [],
    },
    {
      id: "poland",
      ...meta,
      name: "Poland",
      country: "Poland",
      slug: "poland",
      flag: "PL",
      primary: false,
      order: 2,
      tagline: "Accessible European education in a fast-growing economy.",
      description:
        "Poland offers English-taught programmes at comparatively accessible tuition and living costs, with established universities in lively student cities.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Comparatively affordable tuition and living costs",
        "Wide range of English-taught programmes",
        "Established medical, technical and business universities",
      ],
      lifestyle: ["Vibrant student cities", "Well connected to the rest of the EU"],
      cities: ["Warsaw", "Kraków", "Wrocław", "Gdańsk", "Poznań"],
      universities: [],
    },
    {
      id: "portugal",
      ...meta,
      name: "Portugal",
      country: "Portugal",
      slug: "portugal",
      flag: "PT",
      primary: false,
      order: 3,
      tagline: "Atlantic cities with a relaxed, international student life.",
      description:
        "Portugal pairs reputable public universities with a welcoming, internationally minded lifestyle and a moderate cost of living compared with much of Western Europe.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Reputable public universities in Lisbon, Porto and Coimbra",
        "Moderate living costs by Western European standards",
        "Growing technology and start-up scene",
      ],
      lifestyle: ["Mild climate and coastal cities", "Safe, welcoming atmosphere"],
      cities: ["Lisbon", "Porto", "Coimbra", "Braga"],
      universities: [],
    },
    {
      id: "austria",
      ...meta,
      name: "Austria",
      country: "Austria",
      slug: "austria",
      flag: "AT",
      primary: false,
      order: 4,
      tagline: "Central European quality with an exceptional quality of life.",
      description:
        "Austria's public universities offer strong academic traditions with moderate tuition for non-EU students, in cities regularly ranked among the most liveable in the world.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Moderate tuition at public universities for most non-EU students",
        "Strong music, arts, sciences and technical universities",
        "Close cultural and linguistic ties with Germany",
      ],
      lifestyle: ["Very high quality of life", "Alpine landscapes within easy reach"],
      cities: ["Vienna", "Graz", "Innsbruck", "Salzburg", "Linz"],
      universities: [],
    },
  ],

  universities: [
    {
      id: "sample-tum",
      ...meta,
      sample: true,
      name: "Technical University of Munich",
      country: "Germany",
      city: "Munich",
      logo: "",
      image: "",
      description: "Public technical university known for engineering, natural sciences, computing and management.",
      programs: ["Informatics", "Mechanical Engineering", "Management"],
      fields: ["Engineering", "Computer Science", "Business"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "Tuition fees apply to most non-EU students since 2024/25. Verify current amounts on the official website.",
      applicationInfo: "Applications are typically submitted directly via the university's online portal.",
      institutionType: "Public",
      website: "https://www.tum.de/en/",
    },
    {
      id: "sample-rwth",
      ...meta,
      sample: true,
      name: "RWTH Aachen University",
      country: "Germany",
      city: "Aachen",
      logo: "",
      image: "",
      description: "Large public technical university with a strong engineering and applied research focus.",
      programs: ["Electrical Engineering", "Data Science", "Automotive Engineering"],
      fields: ["Engineering", "Computer Science"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "No general tuition fees for most programmes; a semester contribution applies. Verify before applying.",
      applicationInfo: "Some programmes use uni-assist for international applicants.",
      institutionType: "Public",
      website: "https://www.rwth-aachen.de/",
    },
    {
      id: "sample-tu-berlin",
      ...meta,
      sample: true,
      name: "Technische Universität Berlin",
      country: "Germany",
      city: "Berlin",
      logo: "",
      image: "",
      description: "Public technical university in the capital with a broad range of engineering and science programmes.",
      programs: ["Computer Science", "Urban Planning", "Energy Engineering"],
      fields: ["Engineering", "Computer Science", "Architecture"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "No general tuition fees for most programmes; a semester contribution applies. Verify before applying.",
      applicationInfo: "Application routes vary by programme; check the programme page.",
      institutionType: "Public",
      website: "https://www.tu.berlin/en/",
    },
    {
      id: "sample-heidelberg",
      ...meta,
      sample: true,
      name: "Heidelberg University",
      country: "Germany",
      city: "Heidelberg",
      logo: "",
      image: "",
      description: "Germany's oldest university, with strengths across life sciences, medicine, physics and humanities.",
      programs: ["Molecular Biosciences", "Physics", "Scientific Computing"],
      fields: ["Natural Sciences", "Medicine & Health"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition:
        "Located in Baden-Württemberg, where tuition fees apply to most non-EU students. Verify current amounts.",
      applicationInfo: "Requirements differ strongly between programmes.",
      institutionType: "Public",
      website: "https://www.uni-heidelberg.de/en",
    },
    {
      id: "sample-polimi",
      ...meta,
      sample: true,
      name: "Politecnico di Milano",
      country: "Italy",
      city: "Milan",
      logo: "",
      image: "",
      description: "Public technical university specialising in engineering, architecture and design.",
      programs: ["Architecture", "Design", "Management Engineering"],
      fields: ["Engineering", "Architecture", "Design"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "Italian"],
      tuition: "Tuition is generally income-based. Verify current fee bands on the official website.",
      applicationInfo: "International applications are handled through the university's online portal.",
      institutionType: "Public",
      website: "https://www.polimi.it/en",
    },
    {
      id: "sample-warsaw",
      ...meta,
      sample: true,
      name: "University of Warsaw",
      country: "Poland",
      city: "Warsaw",
      logo: "",
      image: "",
      description: "Poland's largest university, with English-taught programmes across social sciences and sciences.",
      programs: ["International Relations", "Economics", "Computer Science"],
      fields: ["Social Sciences", "Business", "Computer Science"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "Polish"],
      tuition: "Tuition applies to English-taught programmes for most international students. Verify amounts.",
      applicationInfo: "Applications are submitted through the university's online registration system.",
      institutionType: "Public",
      website: "https://en.uw.edu.pl/",
    },
    {
      id: "sample-lisbon",
      ...meta,
      sample: true,
      name: "University of Lisbon",
      country: "Portugal",
      city: "Lisbon",
      logo: "",
      image: "",
      description: "Portugal's largest public university, spanning engineering, sciences, arts and economics.",
      programs: ["Engineering", "Economics", "Architecture"],
      fields: ["Engineering", "Business", "Architecture"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "Portuguese"],
      tuition: "International student tuition applies. Verify current amounts per faculty.",
      applicationInfo: "Admission is handled by each school/faculty.",
      institutionType: "Public",
      website: "https://www.ulisboa.pt/en",
    },
    {
      id: "sample-vienna",
      ...meta,
      sample: true,
      name: "University of Vienna",
      country: "Austria",
      city: "Vienna",
      logo: "",
      image: "",
      description: "One of the largest universities in the German-speaking world, with a wide programme portfolio.",
      programs: ["Data Science", "Economics", "Molecular Biology"],
      fields: ["Natural Sciences", "Business", "Social Sciences"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "Moderate per-semester tuition for most non-EU students. Verify current amounts.",
      applicationInfo: "Online application with document upload; deadlines vary by programme.",
      institutionType: "Public",
      website: "https://www.univie.ac.at/en/",
    },
  ],

  faqs: [
    {
      id: "faq-guarantee",
      ...meta,
      order: 0,
      question: "Can you guarantee admission or a visa?",
      answer:
        "No. Admission decisions are made by universities and visa decisions by the relevant embassy or authorities. We help you prepare the strongest possible application and explain requirements clearly, but nobody can honestly guarantee an outcome.",
    },
    {
      id: "faq-tuition",
      ...meta,
      order: 1,
      question: "Is studying in Germany really free?",
      answer:
        "Most public universities in Germany charge no general tuition for most programmes, but students pay a semester contribution, and some states and universities charge tuition to non-EU students. Living costs and the financial proof required for a visa must also be planned for.",
    },
    {
      id: "faq-language",
      ...meta,
      order: 2,
      question: "Do I need to speak German?",
      answer:
        "Not always. Many master's and some bachelor's programmes are taught in English. German skills still help significantly with daily life, part-time work and careers, and are required for German-taught programmes.",
    },
  ],

  settings: [
    {
      id: "settings",
      ...meta,
      // TEMPORARY business WhatsApp number supplied by AVIORA EDU — change it in Admin → Business settings.
      whatsappNumber: "4915217595531",
      whatsappMessage: "Hello AVIORA EDU, I would like to discuss studying in Europe.",
      businessEmail: "",
      phone: "",
    },
  ],

  dreamStories: [],
  reviews: [],
  team: [],
  submissions: [],
};
