import type { CollectionMap, CollectionName } from "./schemas";

/**
 * Initial content used until an administrator saves changes (which writes to
 * CONTENT_DIR). Editorial destination copy is general and non-absolute.
 *
 * - Universities are SAMPLE entries (`sample: true`) of well-known public
 *   institutions for layout/search development. They are informational only,
 *   imply NO partnership, and fees/requirements must be verified before launch.
 * - Dream Stories, Reviews and Team are intentionally EMPTY: only real,
 *   consented content may be added through the admin dashboard.
 */
const t = "2026-01-01T00:00:00.000Z";
const meta = { published: true, createdAt: t, updatedAt: t };

export const seed: { [K in CollectionName]: CollectionMap[K][] } = {
  homepage: [
    {
      id: "homepage",
      ...meta,
      heroHeadline: "Study in Germany, planned properly.",
      heroSubheadline: "Admission, visa and arrival — explained honestly.",
      heroMessage:
        "We help students choose the right German or European university, prepare a clean application and understand the visa process before they book a flight.",
      introStatement:
        "Most of the students we speak to come from Pakistan, India, Bangladesh and the Gulf. They usually have the grades — what they need is someone to explain the German system clearly, check the details and stay reachable until they arrive.",
      aboutWho:
        "AVIORA EDU is an education consultancy focused on Germany and a small, deliberately chosen set of European study destinations: Italy, Poland, Portugal and Austria.",
      aboutWhat:
        "We help students assess their profile, shortlist suitable universities and programs, prepare strong application documents, understand visa requirements and plan for life in Europe.",
      aboutWhy:
        "We keep our focus narrow so our guidance can be deep. We explain requirements plainly, never promise outcomes we do not control, and stay with students from the first conversation to their first weeks abroad.",
      heroHeadlineDe: "Studieren in Deutschland – richtig geplant.",
      heroSubheadlineDe: "Zulassung, Visum und Ankunft – ehrlich erklärt.",
      heroMessageDe:
        "Wir helfen Studierenden, die passende Hochschule in Deutschland oder Europa zu finden, eine saubere Bewerbung vorzubereiten und das Visumverfahren zu verstehen – bevor sie einen Flug buchen.",
      introStatementDe:
        "Die meisten Studierenden, mit denen wir sprechen, kommen aus Pakistan, Indien, Bangladesch und den Golfstaaten. Die Noten haben sie meist – was fehlt, ist jemand, der das deutsche System klar erklärt, die Details prüft und bis zur Ankunft erreichbar bleibt.",
      aboutWhoDe:
        "AVIORA EDU ist eine Bildungsberatung mit Schwerpunkt Deutschland und einer bewusst kleinen Auswahl weiterer europäischer Studienziele: Italien, Polen, Portugal und Österreich.",
      aboutWhatDe:
        "Wir helfen Studierenden, ihr Profil realistisch einzuschätzen, passende Hochschulen und Studiengänge auszuwählen, starke Bewerbungsunterlagen vorzubereiten, die Visumvoraussetzungen zu verstehen und das Leben in Europa zu planen.",
      aboutWhyDe:
        "Wir bleiben bewusst fokussiert, damit unsere Beratung in die Tiefe gehen kann. Wir erklären Anforderungen verständlich, versprechen keine Ergebnisse, die wir nicht beeinflussen können, und begleiten Studierende vom ersten Gespräch bis zu den ersten Wochen im Ausland.",
    },
  ],

  destinations: [
    {
      id: "germany",
      ...meta,
      name: "Germany",
      country: "Germany",
      slug: "germany",
      flag: "DE",
      primary: true,
      order: 0,
      tagline: "Research-driven universities at the heart of Europe.",
      description:
        "Germany combines internationally respected public universities, a strong research culture and one of Europe's largest economies. Many programs are taught in English at master's level, and most public universities charge low or no tuition fees for the majority of programs — though a semester contribution applies and some federal states or universities charge non-EU students.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Public universities with low or no tuition for most programs (rules vary by state)",
        "Strong engineering, computer science, natural science and business faculties",
        "Universities of Applied Sciences with practice-oriented, industry-linked degrees",
        "Post-study residence permit options to search for work after graduation",
        "Degrees recognized across the European Higher Education Area",
      ],
      lifestyle: [
        "Excellent public transport and semester tickets in many cities",
        "Large international student communities in Berlin, Munich, Hamburg and beyond",
        "Central location for travel across Europe",
      ],
      cities: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Aachen", "Heidelberg", "Stuttgart", "Cologne"],
      nameDe: "Deutschland",
      taglineDe: "Forschungsstarke Hochschulen im Herzen Europas.",
      descriptionDe:
        "Deutschland verbindet international angesehene staatliche Hochschulen, eine starke Forschungskultur und eine der größten Volkswirtschaften Europas. Viele Masterstudiengänge werden auf Englisch angeboten, und die meisten staatlichen Hochschulen erheben für die Mehrheit der Studiengänge keine oder nur geringe Studiengebühren – ein Semesterbeitrag fällt jedoch an, und einzelne Bundesländer oder Hochschulen verlangen Gebühren von Studierenden aus Nicht-EU-Staaten.",
      benefitsDe: [
        "Staatliche Hochschulen mit geringen oder keinen Studiengebühren für die meisten Studiengänge (je nach Bundesland unterschiedlich)",
        "Starke Fakultäten in Ingenieurwesen, Informatik, Naturwissenschaften und Wirtschaft",
        "Hochschulen für angewandte Wissenschaften mit praxisnahen, industrienahen Abschlüssen",
        "Aufenthaltstitel zur Arbeitssuche nach dem Abschluss",
        "Abschlüsse, die im gesamten Europäischen Hochschulraum anerkannt sind",
      ],
      lifestyleDe: [
        "Sehr guter öffentlicher Nahverkehr und Semestertickets in vielen Städten",
        "Große internationale Studierendengemeinschaften in Berlin, München, Hamburg und darüber hinaus",
        "Zentrale Lage für Reisen durch ganz Europa",
      ],
      universities: [],
    },
    {
      id: "italy",
      ...meta,
      name: "Italy",
      country: "Italy",
      slug: "italy",
      flag: "IT",
      primary: false,
      order: 1,
      tagline: "Historic universities, design, architecture and engineering.",
      description:
        "Italy is home to some of the world's oldest universities alongside modern technical institutes. Public universities often use income-based tuition, and a growing number of degrees are taught in English.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Income-based tuition at many public universities",
        "Strengths in architecture, design, engineering and economics",
        "Regional scholarship schemes for eligible students",
      ],
      lifestyle: ["Rich cultural life and heritage cities", "Mediterranean climate and cuisine"],
      cities: ["Milan", "Rome", "Bologna", "Turin", "Padua"],
      nameDe: "Italien",
      taglineDe: "Traditionsreiche Universitäten für Design, Architektur und Ingenieurwesen.",
      descriptionDe:
        "Italien beheimatet einige der ältesten Universitäten der Welt und zugleich moderne technische Hochschulen. Staatliche Universitäten berechnen Studiengebühren oft einkommensabhängig, und immer mehr Studiengänge werden auf Englisch angeboten.",
      benefitsDe: ["Einkommensabhängige Studiengebühren an vielen staatlichen Universitäten", "Stärken in Architektur, Design, Ingenieurwesen und Wirtschaft", "Regionale Stipendienprogramme für berechtigte Studierende"],
      lifestyleDe: ["Reiches kulturelles Leben und historische Städte", "Mediterranes Klima und italienische Küche"],
      universities: [],
    },
    {
      id: "poland",
      ...meta,
      name: "Poland",
      country: "Poland",
      slug: "poland",
      flag: "PL",
      primary: false,
      order: 2,
      tagline: "Accessible European education in a fast-growing economy.",
      description:
        "Poland offers English-taught programs at comparatively accessible tuition and living costs, with established universities in lively student cities.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Comparatively affordable tuition and living costs",
        "Wide range of English-taught programs",
        "Established medical, technical and business universities",
      ],
      lifestyle: ["Vibrant student cities", "Well connected to the rest of the EU"],
      cities: ["Warsaw", "Kraków", "Wrocław", "Gdańsk", "Poznań"],
      nameDe: "Polen",
      taglineDe: "Gut zugängliche europäische Bildung in einer wachsenden Volkswirtschaft.",
      descriptionDe:
        "Polen bietet englischsprachige Studiengänge zu vergleichsweise moderaten Studien- und Lebenshaltungskosten – an etablierten Universitäten in lebendigen Studentenstädten.",
      benefitsDe: ["Vergleichsweise günstige Studiengebühren und Lebenshaltungskosten", "Große Auswahl an englischsprachigen Studiengängen", "Etablierte medizinische, technische und wirtschaftswissenschaftliche Hochschulen"],
      lifestyleDe: ["Lebendige Studentenstädte", "Gute Verbindungen in die übrige EU"],
      universities: [],
    },
    {
      id: "portugal",
      ...meta,
      name: "Portugal",
      country: "Portugal",
      slug: "portugal",
      flag: "PT",
      primary: false,
      order: 3,
      tagline: "Atlantic cities with a relaxed, international student life.",
      description:
        "Portugal pairs reputable public universities with a welcoming, internationally minded lifestyle and a moderate cost of living compared with much of Western Europe.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Reputable public universities in Lisbon, Porto and Coimbra",
        "Moderate living costs by Western European standards",
        "Growing technology and start-up scene",
      ],
      lifestyle: ["Mild climate and coastal cities", "Safe, welcoming atmosphere"],
      cities: ["Lisbon", "Porto", "Coimbra", "Braga"],
      nameDe: "Portugal",
      taglineDe: "Atlantikstädte mit entspanntem, internationalem Studentenleben.",
      descriptionDe:
        "Portugal verbindet angesehene staatliche Universitäten mit einem offenen, international geprägten Lebensstil und im westeuropäischen Vergleich moderaten Lebenshaltungskosten.",
      benefitsDe: ["Angesehene staatliche Universitäten in Lissabon, Porto und Coimbra", "Moderate Lebenshaltungskosten im westeuropäischen Vergleich", "Wachsende Technologie- und Start-up-Szene"],
      lifestyleDe: ["Mildes Klima und Küstenstädte", "Sichere, gastfreundliche Atmosphäre"],
      universities: [],
    },
    {
      id: "austria",
      ...meta,
      name: "Austria",
      country: "Austria",
      slug: "austria",
      flag: "AT",
      primary: false,
      order: 4,
      tagline: "Strong public universities and a high quality of life.",
      description:
        "Austria's public universities offer strong academic traditions with moderate tuition for non-EU students, in cities regularly ranked among the most liveable in the world.",
      heroImage: "",
      gallery: [],
      benefits: [
        "Moderate tuition at public universities for most non-EU students",
        "Strong music, arts, sciences and technical universities",
        "Close cultural and linguistic ties with Germany",
      ],
      lifestyle: ["Very high quality of life", "Alpine landscapes within easy reach"],
      cities: ["Vienna", "Graz", "Innsbruck", "Salzburg", "Linz"],
      nameDe: "Österreich",
      taglineDe: "Starke staatliche Universitäten und eine hohe Lebensqualität.",
      descriptionDe:
        "Österreichs staatliche Universitäten bieten eine starke akademische Tradition bei moderaten Studiengebühren für Studierende aus Nicht-EU-Staaten – in Städten, die regelmäßig zu den lebenswertesten der Welt gezählt werden.",
      benefitsDe: ["Moderate Studiengebühren an staatlichen Universitäten für die meisten Nicht-EU-Studierenden", "Starke Universitäten für Musik, Kunst, Naturwissenschaften und Technik", "Enge kulturelle und sprachliche Verbindung zu Deutschland"],
      lifestyleDe: ["Sehr hohe Lebensqualität", "Alpenlandschaften in greifbarer Nähe"],
      universities: [],
    },
  ],

  universities: [
    {
      id: "sample-tum",
      ...meta,
      sample: true,
      name: "Technical University of Munich",
      country: "Germany",
      city: "Munich",
      logo: "",
      image: "",
      description: "Public technical university known for engineering, natural sciences, computing and management.",
      programs: ["Informatics", "Mechanical Engineering", "Management"],
      fields: ["Engineering", "Computer Science", "Business"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "Tuition fees apply to most non-EU students since 2024/25. Verify current amounts on the official website.",
      applicationInfo: "Applications are typically submitted directly via the university's online portal.",
      institutionType: "Public",
      website: "https://www.tum.de/en/",
      descriptionDe: "Staatliche Technische Universität mit Schwerpunkten in Ingenieurwesen, Naturwissenschaften, Informatik und Management.",
      tuitionDe: "Seit dem Wintersemester 2024/25 zahlen die meisten Studierenden aus Nicht-EU-Staaten Studiengebühren. Aktuelle Beträge bitte auf der offiziellen Website prüfen.",
      applicationInfoDe: "Bewerbungen werden in der Regel direkt über das Online-Portal der Universität eingereicht.",
    },
    {
      id: "sample-rwth",
      ...meta,
      sample: true,
      name: "RWTH Aachen University",
      country: "Germany",
      city: "Aachen",
      logo: "",
      image: "",
      description: "Large public technical university with a strong engineering and applied research focus.",
      programs: ["Electrical Engineering", "Data Science", "Automotive Engineering"],
      fields: ["Engineering", "Computer Science"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "No general tuition fees for most programs; a semester contribution applies. Verify before applying.",
      applicationInfo: "Some programs use uni-assist for international applicants.",
      institutionType: "Public",
      website: "https://www.rwth-aachen.de/",
      descriptionDe: "Große staatliche Technische Hochschule mit starkem Fokus auf Ingenieurwesen und angewandte Forschung.",
      tuitionDe: "Für die meisten Studiengänge keine allgemeinen Studiengebühren; ein Semesterbeitrag fällt an. Bitte vor der Bewerbung prüfen.",
      applicationInfoDe: "Einige Studiengänge nutzen uni-assist für internationale Bewerbungen.",
    },
    {
      id: "sample-tu-berlin",
      ...meta,
      sample: true,
      name: "Technische Universität Berlin",
      country: "Germany",
      city: "Berlin",
      logo: "",
      image: "",
      description: "Public technical university in the capital with a broad range of engineering and science programs.",
      programs: ["Computer Science", "Urban Planning", "Energy Engineering"],
      fields: ["Engineering", "Computer Science", "Architecture"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "No general tuition fees for most programs; a semester contribution applies. Verify before applying.",
      applicationInfo: "Application routes vary by program; check the program page.",
      institutionType: "Public",
      website: "https://www.tu.berlin/en/",
      descriptionDe: "Staatliche Technische Universität in der Hauptstadt mit einem breiten Angebot in Ingenieur- und Naturwissenschaften.",
      tuitionDe: "Für die meisten Studiengänge keine allgemeinen Studiengebühren; ein Semesterbeitrag fällt an. Bitte vor der Bewerbung prüfen.",
      applicationInfoDe: "Der Bewerbungsweg unterscheidet sich je nach Studiengang; Details stehen auf der jeweiligen Studiengangsseite.",
    },
    {
      id: "sample-heidelberg",
      ...meta,
      sample: true,
      name: "Heidelberg University",
      country: "Germany",
      city: "Heidelberg",
      logo: "",
      image: "",
      description: "Germany's oldest university, with strengths across life sciences, medicine, physics and humanities.",
      programs: ["Molecular Biosciences", "Physics", "Scientific Computing"],
      fields: ["Natural Sciences", "Medicine & Health"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition:
        "Located in Baden-Württemberg, where tuition fees apply to most non-EU students. Verify current amounts.",
      applicationInfo: "Requirements differ strongly between programs.",
      institutionType: "Public",
      website: "https://www.uni-heidelberg.de/en",
      descriptionDe: "Deutschlands älteste Universität mit Stärken in Lebenswissenschaften, Medizin, Physik und Geisteswissenschaften.",
      tuitionDe: "Liegt in Baden-Württemberg, wo die meisten Studierenden aus Nicht-EU-Staaten Studiengebühren zahlen. Aktuelle Beträge bitte prüfen.",
      applicationInfoDe: "Die Anforderungen unterscheiden sich stark zwischen den Studiengängen.",
    },
    {
      id: "sample-polimi",
      ...meta,
      sample: true,
      name: "Politecnico di Milano",
      country: "Italy",
      city: "Milan",
      logo: "",
      image: "",
      description: "Public technical university specializing in engineering, architecture and design.",
      programs: ["Architecture", "Design", "Management Engineering"],
      fields: ["Engineering", "Architecture", "Design"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "Italian"],
      tuition: "Tuition is generally income-based. Verify current fee bands on the official website.",
      applicationInfo: "International applications are handled through the university's online portal.",
      institutionType: "Public",
      website: "https://www.polimi.it/en",
      descriptionDe: "Staatliche Technische Universität mit Spezialisierung auf Ingenieurwesen, Architektur und Design.",
      tuitionDe: "Die Studiengebühren sind in der Regel einkommensabhängig. Aktuelle Gebührenstufen bitte auf der offiziellen Website prüfen.",
      applicationInfoDe: "Internationale Bewerbungen laufen über das Online-Portal der Universität.",
    },
    {
      id: "sample-warsaw",
      ...meta,
      sample: true,
      name: "University of Warsaw",
      country: "Poland",
      city: "Warsaw",
      logo: "",
      image: "",
      description: "Poland's largest university, with English-taught programs across social sciences and sciences.",
      programs: ["International Relations", "Economics", "Computer Science"],
      fields: ["Social Sciences", "Business", "Computer Science"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "Polish"],
      tuition: "Tuition applies to English-taught programs for most international students. Verify amounts.",
      applicationInfo: "Applications are submitted through the university's online registration system.",
      institutionType: "Public",
      website: "https://en.uw.edu.pl/",
      descriptionDe: "Polens größte Universität mit englischsprachigen Studiengängen in Sozial- und Naturwissenschaften.",
      tuitionDe: "Für englischsprachige Studiengänge zahlen die meisten internationalen Studierenden Studiengebühren. Beträge bitte prüfen.",
      applicationInfoDe: "Bewerbungen werden über das Online-Registrierungssystem der Universität eingereicht.",
    },
    {
      id: "sample-lisbon",
      ...meta,
      sample: true,
      name: "University of Lisbon",
      country: "Portugal",
      city: "Lisbon",
      logo: "",
      image: "",
      description: "Portugal's largest public university, spanning engineering, sciences, arts and economics.",
      programs: ["Engineering", "Economics", "Architecture"],
      fields: ["Engineering", "Business", "Architecture"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "Portuguese"],
      tuition: "International student tuition applies. Verify current amounts per faculty.",
      applicationInfo: "Admission is handled by each school/faculty.",
      institutionType: "Public",
      website: "https://www.ulisboa.pt/en",
      descriptionDe: "Portugals größte staatliche Universität mit Ingenieurwesen, Naturwissenschaften, Kunst und Wirtschaft.",
      tuitionDe: "Für internationale Studierende fallen Studiengebühren an. Aktuelle Beträge je Fakultät bitte prüfen.",
      applicationInfoDe: "Die Zulassung erfolgt über die jeweilige Fakultät.",
    },
    {
      id: "sample-vienna",
      ...meta,
      sample: true,
      name: "University of Vienna",
      country: "Austria",
      city: "Vienna",
      logo: "",
      image: "",
      description: "One of the largest universities in the German-speaking world, with a wide program portfolio.",
      programs: ["Data Science", "Economics", "Molecular Biology"],
      fields: ["Natural Sciences", "Business", "Social Sciences"],
      studyLevels: ["Bachelor", "Master", "PhD"],
      language: ["English", "German"],
      tuition: "Moderate per-semester tuition for most non-EU students. Verify current amounts.",
      applicationInfo: "Online application with document upload; deadlines vary by program.",
      institutionType: "Public",
      website: "https://www.univie.ac.at/en/",
      descriptionDe: "Eine der größten Universitäten im deutschsprachigen Raum mit einem sehr breiten Studienangebot.",
      tuitionDe: "Moderate Studiengebühren pro Semester für die meisten Nicht-EU-Studierenden. Aktuelle Beträge bitte prüfen.",
      applicationInfoDe: "Online-Bewerbung mit Upload der Unterlagen; Fristen variieren je nach Studiengang.",
    },
  ],

  faqs: [
    {
      id: "faq-guarantee",
      ...meta,
      order: 0,
      questionDe: "Können Sie eine Zulassung oder ein Visum garantieren?",
      answerDe:
        "Nein. Über die Zulassung entscheiden die Hochschulen, über das Visum die zuständige Botschaft bzw. Behörde. Wir helfen Ihnen, die bestmögliche Bewerbung vorzubereiten, und erklären die Anforderungen klar – ein Ergebnis kann aber niemand seriös garantieren.",
      question: "Can you guarantee admission or a visa?",
      answer:
        "No. Admission decisions are made by universities and visa decisions by the relevant embassy or authorities. We help you prepare the strongest possible application and explain requirements clearly, but nobody can honestly guarantee an outcome.",
    },
    {
      id: "faq-tuition",
      ...meta,
      order: 1,
      questionDe: "Ist ein Studium in Deutschland wirklich kostenlos?",
      answerDe:
        "Die meisten staatlichen Hochschulen erheben für die meisten Studiengänge keine allgemeinen Studiengebühren. Ein Semesterbeitrag fällt jedoch an, und einige Bundesländer und Hochschulen verlangen Gebühren von Studierenden aus Nicht-EU-Staaten. Lebenshaltungskosten und der für das Visum nötige Finanzierungsnachweis müssen ebenfalls eingeplant werden.",
      question: "Is studying in Germany really free?",
      answer:
        "Most public universities in Germany charge no general tuition for most programs, but students pay a semester contribution, and some states and universities charge tuition to non-EU students. Living costs and the financial proof required for a visa must also be planned for.",
    },
    {
      id: "faq-language",
      ...meta,
      order: 2,
      questionDe: "Muss ich Deutsch sprechen?",
      answerDe:
        "Nicht unbedingt. Viele Master- und einige Bachelorstudiengänge werden auf Englisch unterrichtet. Deutschkenntnisse helfen aber sehr im Alltag, beim Nebenjob und bei der späteren Karriere – und für deutschsprachige Studiengänge sind sie Voraussetzung.",
      question: "Do I need to speak German?",
      answer:
        "Not always. Many master's and some bachelor's programs are taught in English. German skills still help significantly with daily life, part-time work and careers, and are required for German-taught programs.",
    },
  ],

  settings: [
    {
      id: "settings",
      ...meta,
      // TEMPORARY business WhatsApp number supplied by AVIORA EDU — change it in Admin → Business settings.
      whatsappNumber: "4915217595531",
      whatsappMessage: "Hello AVIORA EDU, I would like to discuss studying in Europe.",
      whatsappMessageDe: "Hallo AVIORA EDU, ich möchte mich über ein Studium in Europa informieren.",
      legalAddress: "",
      legalForm: "",
      vatId: "",
      registerEntry: "",
      disputeResolution: "",
      pkEntityName: "",
      pkRegistration: "",
      pkNtn: "",
      pkAddress: "",
      businessEmail: "naveedahmedmahesar@gmail.com",
      phone: "",
      businessName: "AVIORA EDU",
      siteUrl: "",
      // Home-based business: city and country only. Never add a street address unless AVIORA EDU provides one.
      addressStreet: "",
      addressPostalCode: "",
      addressCity: "Berlin",
      addressCountry: "Germany",
      socialInstagram: "",
      socialFacebook: "",
      socialLinkedin: "",
      socialYoutube: "",
      socialTiktok: "",
    },
  ],

  dreamStories: [],
  reviews: [],
  // Founder details supplied by AVIORA EDU. No photo and no credentials beyond what was provided.
  team: [
    {
      id: "founder",
      ...meta,
      name: "Naveed Ahmed",
      role: "Founder & Lead Immigration Consultant",
      bio: "Naveed Ahmed has spent more than ten years guiding students through education decisions. As a German and Pakistani national based in Berlin, he knows both sides of the move — the questions families in Pakistan ask, and what German universities and authorities expect. He founded AVIORA EDU to give students straight answers, realistic plans and a contact who stays reachable.",
      photo: "",
      order: 0,
      nationality: "German & Pakistani",
      experience: "10+ years in education consultancy",
      location: "Berlin, Germany",
      locationDe: "Berlin, Deutschland",
      logoText: "",
      logoImage: "",
      displayMode: "logo",
      roleDe: "Gründer & Lead Immigration Consultant",
      bioDe:
        "Naveed Ahmed begleitet seit mehr als zehn Jahren Studierende bei ihren Bildungsentscheidungen. Als deutscher und pakistanischer Staatsangehöriger mit Sitz in Berlin kennt er beide Seiten des Weges: die Fragen, die Familien in Pakistan bewegen, und die Erwartungen deutscher Hochschulen und Behörden. Mit AVIORA EDU möchte er Studierenden ehrliche Antworten, realistische Pläne und einen Ansprechpartner geben, der erreichbar bleibt.",
      nationalityDe: "Deutsch & pakistanisch",
      experienceDe: "Über 10 Jahre Erfahrung in der Bildungsberatung",
    },
  ],
  submissions: [],
};
