import type { CollectionName } from "@/lib/content/schemas";

export type Field =
  | { key: string; label: string; type: "text" | "textarea" | "url" | "number" | "bool" | "date" | "media-image" | "media-video" | "media-redact" | "list"; help?: string }
  | { key: string; label: string; type: "select" | "multi"; options: string[]; help?: string };

export const collectionMeta: Record<CollectionName, { label: string; titleKey: string; subtitleKey?: string; fields: Field[]; canCreate: boolean; single?: boolean }> = {
  settings: {
    label: "Settings · Contact information",
    titleKey: "businessName",
    subtitleKey: "businessEmail",
    canCreate: false,
    single: true,
    fields: [
      { key: "businessName", label: "Business name", type: "text", help: "Used in the footer, page titles and structured data." },
      { key: "businessEmail", label: "Business email", type: "text", help: "Shown on the contact section and footer, and used for lead notifications when email sending is configured. Leave empty to hide." },
      { key: "phone", label: "Phone number (optional)", type: "text", help: "e.g. +49 152 17595531. Leave empty to hide." },
      { key: "whatsappNumber", label: "WhatsApp number", type: "text", help: "International format, digits only — e.g. 4915217595531 (spaces, + and brackets are removed automatically). Leave empty to hide WhatsApp." },
      { key: "whatsappMessage", label: "WhatsApp pre-filled message", type: "textarea" },
      { key: "siteUrl", label: "Website URL", type: "text", help: "e.g. https://www.yourdomain.com — used for canonical URLs, sitemap and structured data. Leave empty to use NEXT_PUBLIC_SITE_URL." },
      { key: "addressStreet", label: "Address — street (optional)", type: "text", help: "Leave empty for a home-based business. Only enter a real address you want published — it appears in the footer and in structured data. City and country alone are shown as the location." },
      { key: "addressPostalCode", label: "Address — postal code", type: "text" },
      { key: "addressCity", label: "Address — city", type: "text" },
      { key: "addressCountry", label: "Address — country", type: "text" },
      { key: "socialInstagram", label: "Instagram URL", type: "url", help: "Only add accounts that exist. https:// links." },
      { key: "socialFacebook", label: "Facebook URL", type: "url" },
      { key: "socialLinkedin", label: "LinkedIn URL", type: "url" },
      { key: "socialYoutube", label: "YouTube URL", type: "url" },
      { key: "socialTiktok", label: "TikTok URL", type: "url" },
      { key: "whatsappMessageDe", label: "WhatsApp pre-filled message (German)", type: "textarea" },
      { key: "legalAddress", label: "Legal — address for Impressum & privacy policy", type: "textarea", help: "Street, postal code and city where legal post can be delivered (required by § 5 DDG). Shown only on the legal pages, not in the footer. A business/service address can be used instead of a home address." },
      { key: "legalForm", label: "Legal — legal form", type: "text", help: "e.g. Einzelunternehmen (sole proprietor). Only enter what is registered." },
      { key: "vatId", label: "Legal — VAT ID (USt-IdNr.)", type: "text", help: "Only if one has been issued." },
      { key: "registerEntry", label: "Legal — commercial register entry", type: "text", help: "Court and number, only if registered." },
      { key: "disputeResolution", label: "Legal — consumer dispute resolution statement (§ 36 VSBG)", type: "textarea" },
      { key: "pkEntityName", label: "Pakistan — registered entity name", type: "text", help: "Leave empty until a Pakistani entity or branch is actually registered." },
      { key: "pkRegistration", label: "Pakistan — SECP registration number", type: "text" },
      { key: "pkNtn", label: "Pakistan — NTN (tax number)", type: "text" },
      { key: "pkAddress", label: "Pakistan — Karachi address", type: "textarea", help: "Only once the Karachi presence exists." },
    ],
  },
  homepage: {
    label: "Homepage content",
    titleKey: "heroHeadline",
    canCreate: false,
    single: true,
    fields: [
      { key: "heroHeadline", label: "Hero headline", type: "text" },
      { key: "heroSubheadline", label: "Hero supporting headline", type: "text" },
      { key: "heroMessage", label: "Hero message", type: "textarea" },
      { key: "introStatement", label: "Intro statement", type: "textarea" },
      { key: "aboutWho", label: "About — who we are", type: "textarea" },
      { key: "aboutWhat", label: "About — what we do", type: "textarea" },
      { key: "aboutWhy", label: "About — why students choose us", type: "textarea" },
      { key: "heroHeadlineDe", label: "Hero headline (German)", type: "text" },
      { key: "heroSubheadlineDe", label: "Hero supporting headline (German)", type: "text" },
      { key: "heroMessageDe", label: "Hero message (German)", type: "textarea" },
      { key: "introStatementDe", label: "Intro statement (German)", type: "textarea" },
      { key: "aboutWhoDe", label: "About — who we are (German)", type: "textarea" },
      { key: "aboutWhatDe", label: "About — what we do (German)", type: "textarea" },
      { key: "aboutWhyDe", label: "About — why students choose us (German)", type: "textarea" },
      { key: "published", label: "Published", type: "bool" },
    ],
  },
  destinations: {
    label: "Destinations",
    titleKey: "name",
    subtitleKey: "tagline",
    canCreate: true,
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "country", label: "Country", type: "text" },
      { key: "slug", label: "URL slug", type: "text", help: "lowercase-with-dashes" },
      { key: "flag", label: "Flag code", type: "select", options: ["DE", "IT", "PL", "PT", "AT"] },
      { key: "primary", label: "Primary destination", type: "bool" },
      { key: "order", label: "Sort order", type: "number" },
      { key: "tagline", label: "Tagline", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "heroImage", label: "Hero image", type: "media-image" },
      { key: "gallery", label: "Gallery image URLs", type: "list", help: "One URL per line (upload images first to get URLs)" },
      { key: "benefits", label: "Benefits", type: "list" },
      { key: "lifestyle", label: "Lifestyle", type: "list" },
      { key: "cities", label: "Cities", type: "list" },
      { key: "universities", label: "Featured universities", type: "list" },
      { key: "nameDe", label: "Name (German)", type: "text" },
      { key: "taglineDe", label: "Tagline (German)", type: "text" },
      { key: "descriptionDe", label: "Description (German)", type: "textarea" },
      { key: "benefitsDe", label: "Benefits (German)", type: "list" },
      { key: "lifestyleDe", label: "Lifestyle (German)", type: "list" },
      { key: "published", label: "Published", type: "bool" },
    ],
  },
  universities: {
    label: "Universities",
    titleKey: "name",
    subtitleKey: "city",
    canCreate: true,
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "country", label: "Country", type: "select", options: ["Germany", "Italy", "Poland", "Portugal", "Austria"] },
      { key: "city", label: "City", type: "text" },
      { key: "institutionType", label: "Type", type: "select", options: ["Public", "Private"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "programs", label: "Programs", type: "list" },
      { key: "fields", label: "Study fields", type: "list" },
      { key: "studyLevels", label: "Study levels", type: "multi", options: ["Foundation", "Bachelor", "Master", "PhD"] },
      { key: "language", label: "Languages", type: "multi", options: ["English", "German", "Italian", "Polish", "Portuguese"] },
      { key: "tuition", label: "Tuition information", type: "textarea" },
      { key: "applicationInfo", label: "Application information", type: "textarea" },
      { key: "website", label: "Official website", type: "url" },
      { key: "logo", label: "Logo (only with permission)", type: "media-image" },
      { key: "image", label: "Image", type: "media-image" },
      { key: "descriptionDe", label: "Description (German)", type: "textarea" },
      { key: "tuitionDe", label: "Tuition information (German)", type: "textarea" },
      { key: "applicationInfoDe", label: "Application information (German)", type: "textarea" },
      { key: "sample", label: "Details still to double-check (internal note)", type: "bool", help: "Not shown on the website. Untick once you have checked fees and requirements on the official site." },
      { key: "published", label: "Published", type: "bool" },
    ],
  },
  dreamStories: {
    label: "Dream Stories · Visa Success",
    titleKey: "studentName",
    subtitleKey: "university",
    canCreate: true,
    fields: [
      { key: "studentName", label: "Student name (internal record)", type: "text", help: "Not shown publicly when a display name is set." },
      { key: "displayName", label: "Public display name", type: "text", help: "Shown on the website, e.g. first name + initial (“Firstname L.”). Leave empty to show the student name — only if the student agreed in writing to publish their full name." },
      { key: "sourceCountry", label: "Source country", type: "select", options: ["Pakistan", "India", "Bangladesh", "United Arab Emirates", "Saudi Arabia", "Qatar", "Oman", "Bahrain", "Other"] },
      { key: "destination", label: "Destination", type: "select", options: ["Germany", "Italy", "Poland", "Portugal", "Austria"] },
      { key: "visaType", label: "Visa type", type: "text", help: "As stated on the visa, e.g. “National visa (D) – Study (§ 16b AufenthG)”." },
      { key: "university", label: "University (only with permission)", type: "text" },
      { key: "program", label: "Program (only with permission)", type: "text" },
      { key: "intake", label: "Intake", type: "text" },
      { key: "successYear", label: "Visa year", type: "text", help: "e.g. 2025" },
      { key: "visaDocument", label: "Redacted visa document", type: "media-redact", help: "Choose the visa photo, cover every personal detail with black boxes, then upload. Only the redacted copy leaves your browser." },
      { key: "photo", label: "Student photo (only with explicit permission)", type: "media-image", help: "Must not show another company's branding." },
      { key: "video", label: "Video", type: "media-video" },
      { key: "story", label: "Success story", type: "textarea", help: "Factual description of the case only — no guarantees, statistics or invented details." },
      { key: "testimonial", label: "Student testimonial (optional)", type: "textarea", help: "Only the student's own words, verbatim. Leave empty if they did not provide one." },
      { key: "consentConfirmed", label: "Written consent obtained", type: "bool", help: "Required: cases are never shown on the website without it." },
      { key: "verified", label: "Verified case", type: "bool", help: "Shows the “Verified Student Success” badge. Only tick if you checked the visa and handled the case." },
      { key: "published", label: "Published", type: "bool" },
    ],
  },
  reviews: {
    label: "Reviews / Testimonials",
    titleKey: "name",
    subtitleKey: "status",
    canCreate: true,
    fields: [
      { key: "name", label: "Client name", type: "text", help: "Real client only, with their permission to publish." },
      { key: "country", label: "Country", type: "text" },
      { key: "review", label: "Review text", type: "textarea", help: "The client's own words. Do not rewrite the meaning." },
      { key: "photo", label: "Client photo (with consent)", type: "media-image", help: "Upload the client's real photo. Leave empty to show their initials." },
      { key: "reviewDate", label: "Date", type: "date" },
      { key: "rating", label: "Rating (0 = no rating, 1–5)", type: "number", help: "Only enter a rating the client actually gave." },
      { key: "destination", label: "Study destination", type: "select", options: ["", "Germany", "Italy", "Poland", "Portugal", "Austria"] },
      { key: "university", label: "University (optional)", type: "text" },
      { key: "program", label: "Program (optional)", type: "text" },
      { key: "source", label: "Source", type: "select", options: ["admin", "website", "external"] },
      { key: "status", label: "Moderation status", type: "select", options: ["approved", "pending", "rejected"] },
      { key: "verified", label: "Verified client", type: "bool", help: "Only tick if you confirmed this person was a client" },
      { key: "featured", label: "Featured", type: "bool", help: "Featured testimonials are shown first and on the homepage." },
      { key: "published", label: "Published", type: "bool", help: "Visible on the website only when Published AND status is approved." },
    ],
  },
  faqs: {
    label: "FAQs",
    titleKey: "question",
    canCreate: true,
    fields: [
      { key: "question", label: "Question", type: "text" },
      { key: "answer", label: "Answer", type: "textarea" },
      { key: "questionDe", label: "Question (German)", type: "text" },
      { key: "answerDe", label: "Answer (German)", type: "textarea" },
      { key: "order", label: "Sort order", type: "number" },
      { key: "published", label: "Published", type: "bool" },
    ],
  },
  team: {
    label: "Team",
    titleKey: "name",
    subtitleKey: "role",
    canCreate: true,
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "role", label: "Role", type: "text" },
      { key: "bio", label: "Bio", type: "textarea" },
      { key: "nationality", label: "Nationality", type: "text", help: "Only facts the person has confirmed." },
      { key: "experience", label: "Experience", type: "text", help: "e.g. 10+ years in education consultancy. Only verified statements." },
      { key: "location", label: "Location", type: "text", help: "e.g. Berlin, Germany. Leave empty to use the location from Settings." },
      { key: "roleDe", label: "Role (German)", type: "text" },
      { key: "bioDe", label: "Bio (German)", type: "textarea" },
      { key: "nationalityDe", label: "Nationality (German)", type: "text" },
      { key: "experienceDe", label: "Experience (German)", type: "text" },
      { key: "locationDe", label: "Location (German)", type: "text" },
      { key: "displayMode", label: "Founder display mode", type: "select", options: ["logo", "photo", "logo-photo"], help: "logo = name wordmark only · photo = photo only · logo-photo = photo with the wordmark. Without a photo the wordmark is always shown." },
      { key: "logoText", label: "Logo / wordmark text", type: "text", help: "Text of the premium wordmark. Leave empty to use the name." },
      { key: "logoImage", label: "Logo image (optional)", type: "media-image", help: "Upload a finished logo (PNG/WebP with transparency works best). Replaces the generated wordmark." },
      { key: "photo", label: "Photo", type: "media-image", help: "Real photo only, with consent. JPG, PNG, WebP or AVIF up to 8 MB." },
      { key: "order", label: "Sort order", type: "number" },
      { key: "published", label: "Published", type: "bool" },
    ],
  },
  submissions: {
    label: "Contact submissions",
    titleKey: "fullName",
    subtitleKey: "email",
    canCreate: false,
    fields: [
      { key: "status", label: "Status", type: "select", options: ["new", "contacted", "closed"] },
      { key: "fullName", label: "Full name", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "country", label: "Country", type: "text" },
      { key: "destination", label: "Destination", type: "text" },
      { key: "studyLevel", label: "Study level", type: "text" },
      { key: "studyField", label: "Study field", type: "text" },
      { key: "intake", label: "Intake", type: "text" },
      { key: "message", label: "Message", type: "textarea" },
    ],
  },
};

export const emptyItem = (name: CollectionName): Record<string, unknown> => {
  const base: Record<string, unknown> = { published: false };
  for (const f of collectionMeta[name].fields) {
    if (f.key in base) continue;
    base[f.key] = f.type === "list" || f.type === "multi" ? [] : f.type === "bool" ? false : f.type === "number" ? 0 : f.type === "select" ? f.options[0] : "";
  }
  if (name === "reviews") Object.assign(base, { source: "admin", status: "approved" });
  return base;
};
